-- FX3 Standard AutoGrade Test.lua
-- Runs only from DaVinci Resolve's internal Workspace > Scripts menu.
-- It never changes, moves, deletes, renames, or overwrites files in ship.

local PROJECT_NAME = "FX3_SLog3_AutoGrade_Test"
local RECOVERY_PROJECT_FOLDER = "FX3_AutoGrade_Internal_Test_Recovery"
local PROJECT_ROOT = os.getenv("FX3_AUTOGRADE_ROOT") or "C:/FX3-SLog3-DaVinci-AutoGrade"
local INPUT_DIR = PROJECT_ROOT .. "/ship"
local OUTPUT_DIR = PROJECT_ROOT .. "/ship_output/test"
local FINAL_REPORT_PATH = PROJECT_ROOT .. "/logs/autograde_test_report.md"
local REPORT_PATH = (os.getenv("TEMP") or ".") .. "/fx3_autograde_test_report.md"
local COMPAT_TIMELINE = "FX3_HEVC_Compatibility_Check"
local INPUT_COLOR_SPACE_LABELS = {
    "S-Gamut3.Cine/S-Log3",
    "Sony S-Gamut3.Cine/S-Log3",
    "Sony S-Gamut3.Cine / S-Log3"
}

-- Replace these public placeholders with three confirmed FX3 test clips.
local TEST_FILES = {
    "FX3_TEST_001.MP4",
    "FX3_TEST_002.MP4",
    "FX3_TEST_003.MP4"
}

local state = {
    phase = "STARTING",
    project_name = PROJECT_NAME,
    selected_files = TEST_FILES,
    imported_files = {},
    project_settings = {},
    input_color_spaces = {},
    compatibility = "NOT_TESTED",
    render_settings = {},
    render_jobs = {},
    outputs = {},
    warnings = {},
    failures = {},
    bulk_ready = false
}

local function normalizeText(value)
    return string.lower((tostring(value or ""):gsub("%s+", "")))
end

local function compactIdentifier(value)
    return string.lower((tostring(value or ""):gsub("[^%w]", "")))
end

local function contains(value, token)
    return string.find(normalizeText(value), normalizeText(token), 1, true) ~= nil
end

local function basename(path)
    local normalized = tostring(path):gsub("\\", "/")
    return normalized:match("([^/]+)$") or normalized
end

local function stem(path)
    return (basename(path):gsub("%.[^%.]+$", ""))
end

local function append(list, value)
    list[#list + 1] = value
end

local function scalar(value)
    local kind = type(value)
    return kind == "string" or kind == "number" or kind == "boolean"
end

local function tableKeysSorted(tbl)
    local keys = {}
    for key, _ in pairs(tbl or {}) do
        append(keys, tostring(key))
    end
    table.sort(keys)
    return keys
end

local function markdownEscape(value)
    local text = tostring(value or "")
    text = text:gsub("|", "\\|")
    text = text:gsub("\r", " ")
    text = text:gsub("\n", " ")
    return text
end

local function writeReport()
    local lines = {}
    append(lines, "# FX3 Standard AutoGrade Test Report")
    append(lines, "")
    append(lines, "Generated by the internal Resolve Lua script. Status: **" .. markdownEscape(state.phase) .. "**")
    append(lines, "")
    append(lines, "## 1. Lua script locations")
    append(lines, "")
    append(lines, "- Project source: `" .. PROJECT_ROOT .. "/scripts/FX3 Standard AutoGrade Test.lua`")
    append(lines, "- User Utility install: `%APPDATA%\\Blackmagic Design\\DaVinci Resolve\\Support\\Fusion\\Scripts\\Utility\\FX3 Standard AutoGrade Test.lua`")
    append(lines, "- Final report destination: `" .. FINAL_REPORT_PATH .. "`")
    append(lines, "")
    append(lines, "## 2. DaVinci project")
    append(lines, "")
    append(lines, "- `" .. PROJECT_NAME .. "`")
    append(lines, "")
    append(lines, "## 3. Three selected test clips")
    append(lines, "")
    for _, name in ipairs(state.selected_files) do
        append(lines, "- `" .. name .. "`")
    end
    append(lines, "")
    append(lines, "Imported so far:")
    append(lines, "")
    if #state.imported_files == 0 then
        append(lines, "- None")
    else
        for _, name in ipairs(state.imported_files) do
            append(lines, "- `" .. name .. "`")
        end
    end
    append(lines, "")
    append(lines, "## 4. HEVC Main 10 decode check")
    append(lines, "")
    append(lines, "- " .. markdownEscape(state.compatibility))
    append(lines, "")
    append(lines, "## 5. Actual project color-management settings")
    append(lines, "")
    local settingKeys = tableKeysSorted(state.project_settings)
    if #settingKeys == 0 then
        append(lines, "- Not available")
    else
        for _, key in ipairs(settingKeys) do
            append(lines, "- `" .. key .. "` = `" .. markdownEscape(state.project_settings[key]) .. "`")
        end
    end
    append(lines, "")
    append(lines, "## 6. Actual Input Color Space")
    append(lines, "")
    local inputKeys = tableKeysSorted(state.input_color_spaces)
    if #inputKeys == 0 then
        append(lines, "- Not set")
    else
        for _, key in ipairs(inputKeys) do
            append(lines, "- `" .. key .. "` = `" .. markdownEscape(state.input_color_spaces[key]) .. "`")
        end
    end
    append(lines, "")
    append(lines, "## 7. Actual/requested render encoding parameters")
    append(lines, "")
    local renderKeys = tableKeysSorted(state.render_settings)
    if #renderKeys == 0 then
        append(lines, "- No render jobs prepared")
    else
        for _, key in ipairs(renderKeys) do
            append(lines, "- `" .. key .. "` = `" .. markdownEscape(state.render_settings[key]) .. "`")
        end
    end
    if #state.render_jobs > 0 then
        append(lines, "")
        append(lines, "Render jobs:")
        append(lines, "")
        for _, job in ipairs(state.render_jobs) do
            append(lines, "- `" .. markdownEscape(job) .. "`")
        end
    end
    append(lines, "")
    append(lines, "## 8. Output paths")
    append(lines, "")
    if #state.outputs == 0 then
        append(lines, "- No output queued yet")
    else
        for _, output in ipairs(state.outputs) do
            append(lines, "- `" .. output .. "`")
        end
    end
    append(lines, "")
    append(lines, "## 9. Failures or warnings")
    append(lines, "")
    if #state.failures == 0 and #state.warnings == 0 then
        append(lines, "- None")
    else
        for _, warning in ipairs(state.warnings) do
            append(lines, "- WARNING: " .. markdownEscape(warning))
        end
        for _, failure in ipairs(state.failures) do
            append(lines, "- FAILURE: " .. markdownEscape(failure))
        end
    end
    append(lines, "")
    append(lines, "## 10. Ready for an explicitly approved batch")
    append(lines, "")
    append(lines, state.bulk_ready and "- Yes" or "- No. Await review and explicit user confirmation.")
    append(lines, "")

    local handle, openError = io.open(REPORT_PATH, "wb")
    if not handle then
        print("REPORT_WRITE_FAILED: " .. tostring(openError))
        return false
    end
    handle:write(table.concat(lines, "\n"))
    handle:close()
    return true
end

local function fail(message)
    append(state.failures, message)
    state.phase = "FAILED"
    writeReport()
    error(message, 0)
end

local function getResolveObject()
    local resolveObject = nil
    if app and app.GetResolve then
        local ok, result = pcall(function() return app:GetResolve() end)
        if ok then resolveObject = result end
    end
    if not resolveObject and type(Resolve) == "function" then
        local ok, result = pcall(function() return Resolve() end)
        if ok then resolveObject = result end
    end
    return resolveObject
end

local function valueEqualsNumber(value, expected)
    local number = tonumber(value)
    return number ~= nil and math.abs(number - expected) < 0.001
end

local function recordSetting(project, key)
    local value = project:GetSetting(key)
    if value ~= nil and tostring(value) ~= "" then
        state.project_settings[key] = value
    end
    return value
end

local function tryProjectSetting(project, key, candidates, validator)
    for _, candidate in ipairs(candidates) do
        local ok = project:SetSetting(key, candidate)
        local actual = project:GetSetting(key)
        if validator(actual) then
            state.project_settings[key] = actual
            return true, actual
        end
    end
    local actual = project:GetSetting(key)
    if actual ~= nil and tostring(actual) ~= "" then
        state.project_settings[key] = actual
    end
    return false, actual
end

local function requireProjectSetting(project, key, candidates, validator, description)
    local ok, actual = tryProjectSetting(project, key, candidates, validator)
    if not ok then
        fail("Could not set and read back " .. description .. " using project setting key '" .. key .. "'. Actual value: " .. tostring(actual))
    end
    return actual
end

local function configureProject(project)
    requireProjectSetting(project, "timelinePlaybackFrameRate", {"59.94", "59.940"}, function(v) return valueEqualsNumber(v, 59.94) end, "playback frame rate 59.94")
    requireProjectSetting(project, "timelineFrameRate", {"59.94", "59.940"}, function(v) return valueEqualsNumber(v, 59.94) end, "timeline frame rate 59.94")
    requireProjectSetting(project, "timelineResolutionWidth", {"3840"}, function(v) return tonumber(v) == 3840 end, "timeline width 3840")
    requireProjectSetting(project, "timelineResolutionHeight", {"2160"}, function(v) return tonumber(v) == 2160 end, "timeline height 2160")

    requireProjectSetting(
        project,
        "colorScienceMode",
        {"davinciYRGBColorManagedv2", "davinciYRGBColorManaged"},
        function(v) return contains(v, "color") and contains(v, "managed") end,
        "DaVinci YRGB Color Managed"
    )

    local customOk = tryProjectSetting(project, "rcmPresetMode", {"Custom"}, function(v) return contains(v, "custom") end)
    local autoOk, autoActual = tryProjectSetting(project, "isAutoColorManage", {"0", "false"}, function(v)
        return tostring(v) == "0" or normalizeText(v) == "false"
    end)
    if not customOk and not autoOk then
        fail("Could not verify that automatic color management is disabled. isAutoColorManage=" .. tostring(autoActual))
    end
    if not autoOk then
        append(state.warnings, "The isAutoColorManage key was unavailable, but rcmPresetMode read back as Custom.")
    end

    tryProjectSetting(project, "separateColorSpaceAndGamma", {"1"}, function(v)
        return tostring(v) == "1" or normalizeText(v) == "true"
    end)

    requireProjectSetting(project, "colorSpaceInput", {"Sony S-Gamut3.Cine", "S-Gamut3.Cine"}, function(v)
        return contains(v, "s-gamut3.cine")
    end, "project input gamut Sony S-Gamut3.Cine")
    requireProjectSetting(project, "colorSpaceInputGamma", {"S-Log3"}, function(v)
        return contains(v, "s-log3")
    end, "project input gamma Sony S-Log3")

    local timelineSpaceOk = tryProjectSetting(project, "colorSpaceTimeline", {"DaVinci WG", "DaVinci Wide Gamut"}, function(v)
        return contains(v, "davinci") and (contains(v, "widegamut") or contains(v, "wg"))
    end)
    local timelineGammaOk = tryProjectSetting(project, "colorSpaceTimelineGamma", {"DaVinci Intermediate"}, function(v)
        return contains(v, "davinci") and contains(v, "intermediate")
    end)
    if not timelineSpaceOk and timelineGammaOk then
        timelineSpaceOk = tryProjectSetting(project, "colorSpaceTimeline", {"DaVinci WG", "DaVinci Wide Gamut"}, function(v)
            return contains(v, "davinci") and (contains(v, "widegamut") or contains(v, "wg"))
        end)
    end
    if not (timelineSpaceOk and timelineGammaOk) then
        local combinedOk = tryProjectSetting(project, "colorSpaceTimeline", {"DaVinci WG/Intermediate", "DaVinci Wide Gamut / Intermediate"}, function(v)
            return contains(v, "davinci") and contains(v, "intermediate")
        end)
        if not combinedOk then
            fail("Could not verify timeline color space as DaVinci Wide Gamut / Intermediate.")
        end
    end

    local outputSpaceOk = tryProjectSetting(project, "colorSpaceOutput", {"Rec.709"}, function(v)
        return contains(v, "rec.709") or contains(v, "rec709")
    end)
    local outputGammaOk = tryProjectSetting(project, "colorSpaceOutputGamma", {"Gamma 2.4", "Gamma2.4"}, function(v)
        return contains(v, "2.4")
    end)
    if not (outputSpaceOk and outputGammaOk) then
        local combinedOk = tryProjectSetting(project, "colorSpaceOutput", {"Rec.709 Gamma 2.4"}, function(v)
            return (contains(v, "rec.709") or contains(v, "rec709")) and contains(v, "2.4")
        end)
        if not combinedOk then
            fail("Could not verify output color space as Rec.709 Gamma 2.4.")
        end
    end

    local allSettings = project:GetSetting() or {}
    for key, value in pairs(allSettings) do
        local lowerKey = string.lower(tostring(key))
        if string.find(lowerKey, "tone", 1, true) or string.find(lowerKey, "gamut", 1, true) or string.find(lowerKey, "mapping", 1, true) then
            if scalar(value) then state.project_settings[key] = value end
        end
    end
end

local function projectExists(projectManager, name)
    local projects = projectManager:GetProjectListInCurrentFolder() or {}
    for _, projectName in ipairs(projects) do
        if projectName == name then return true end
    end
    return false
end

local function rootClips(project)
    return project:GetMediaPool():GetRootFolder():GetClipList() or {}
end

local function clipFilePath(clip)
    local value = clip:GetClipProperty("File Path")
    if value and tostring(value) ~= "" then return tostring(value) end
    local properties = clip:GetClipProperty() or {}
    for key, propertyValue in pairs(properties) do
        local lowerKey = string.lower(tostring(key))
        if lowerKey == "file path" or lowerKey == "filepath" then
            return tostring(propertyValue or "")
        end
    end
    return ""
end

local function findClipByFile(project, fileName)
    for _, clip in ipairs(rootClips(project)) do
        local path = clipFilePath(clip)
        if string.lower(basename(path)) == string.lower(fileName) then
            return clip
        end
    end
    return nil
end

local function importOne(project, fullPath)
    local existing = findClipByFile(project, basename(fullPath))
    if existing then return existing end
    local imported = project:GetMediaPool():ImportMedia({fullPath}) or {}
    local clip = imported[1]
    if not clip then fail("Resolve failed to import: " .. fullPath) end
    return clip
end

local function findInputColorSpaceKey(clip)
    local properties = clip:GetClipProperty() or {}
    for key, _ in pairs(properties) do
        local lowerKey = string.lower(tostring(key))
        if lowerKey == "input color space" then return key end
        if string.find(lowerKey, "input", 1, true) and string.find(lowerKey, "color", 1, true) and string.find(lowerKey, "space", 1, true) then
            return key
        end
    end
    return "Input Color Space"
end

local function setInputColorSpace(project, clip, fileName)
    local key = findInputColorSpaceKey(clip)
    for _, label in ipairs(INPUT_COLOR_SPACE_LABELS) do
        local ok = clip:SetClipProperty(key, label)
        local actual = clip:GetClipProperty(key)
        if ok and contains(actual, "s-gamut3.cine") and contains(actual, "s-log3") then
            state.input_color_spaces[fileName] = actual
            return actual
        end
    end
    local actual = clip:GetClipProperty(key)
    local projectInputSpace = project:GetSetting("colorSpaceInput")
    local projectInputGamma = project:GetSetting("colorSpaceInputGamma")
    local inheritsProject = normalizeText(actual) == "project" or tostring(actual) == "项目"
    local projectInputVerified = contains(projectInputSpace, "s-gamut3.cine") and contains(projectInputGamma, "s-log3")
    if inheritsProject and projectInputVerified then
        local effective = "Project (" .. tostring(actual) .. ") -> " .. tostring(projectInputSpace) .. " / " .. tostring(projectInputGamma)
        state.input_color_spaces[fileName] = effective
        append(state.warnings, "Per-clip Input Color Space is inherited from the verified project default for " .. fileName .. ": " .. effective .. ".")
        return effective
    end
    fail("Could not set and read back Input Color Space for " .. fileName .. ". Key='" .. tostring(key) .. "', actual='" .. tostring(actual) .. "'.")
end

local function findTimeline(project, name)
    for index = 1, project:GetTimelineCount() do
        local timeline = project:GetTimelineByIndex(index)
        if timeline and timeline:GetName() == name then return timeline end
    end
    return nil
end

local function verifyOneClipTimeline(timeline, fileName)
    local items = timeline:GetItemListInTrack("video", 1) or {}
    if #items ~= 1 then
        fail("Existing render timeline does not contain exactly one video item: " .. timeline:GetName())
    end
    local mediaPoolItem = items[1]:GetMediaPoolItem()
    local actualPath = mediaPoolItem and clipFilePath(mediaPoolItem) or ""
    if string.lower(basename(actualPath)) ~= string.lower(fileName) then
        fail("Existing render timeline does not match the expected source clip: " .. timeline:GetName())
    end
end

local function setTimelineGeometry(timeline)
    local required = {
        {"timelineResolutionWidth", "3840", 3840},
        {"timelineResolutionHeight", "2160", 2160},
        {"timelineFrameRate", "59.94", 59.94},
        {"timelinePlaybackFrameRate", "59.94", 59.94}
    }
    for _, entry in ipairs(required) do
        local key, value, expected = entry[1], entry[2], entry[3]
        local ok = timeline:SetSetting(key, value)
        local actual = timeline:GetSetting(key)
        if not ok and not valueEqualsNumber(actual, expected) then
            fail("Could not verify timeline setting " .. key .. "=" .. value .. "; actual=" .. tostring(actual))
        end
    end
end

local function chooseMp4H264(project)
    local formats = project:GetRenderFormats() or {}
    local formatName = nil
    for name, extension in pairs(formats) do
        if normalizeText(name) == "mp4" or normalizeText(extension) == "mp4" then
            formatName = name
            break
        end
    end
    if not formatName then fail("MP4 render format is not available in this Resolve installation.") end

    local codecs = project:GetRenderCodecs(formatName) or {}
    local codecName = nil
    local codecDescription = nil
    for description, name in pairs(codecs) do
        if contains(description, "h.264") or contains(description, "h264") or contains(name, "h.264") or contains(name, "h264") then
            codecName = name
            codecDescription = description
            break
        end
    end
    if not codecName then fail("H.264 is not available for the MP4 format in this Resolve installation.") end

    local ok = project:SetCurrentRenderFormatAndCodec(formatName, codecName)
    local actual = project:GetCurrentRenderFormatAndCodec() or {}
    local formatMatches = normalizeText(actual.format) == normalizeText(formatName)
        or compactIdentifier(actual.format) == "mp4"
    local codecMatches = compactIdentifier(actual.codec) == compactIdentifier(codecName)
        or string.find(compactIdentifier(actual.codec), "h264", 1, true) ~= nil
    if not (formatMatches and codecMatches) then
        fail("Could not verify MP4/H.264 render format and codec. Set returned=" .. tostring(ok)
            .. ", requested format='" .. tostring(formatName) .. "', requested codec='" .. tostring(codecName)
            .. "', actual format='" .. tostring(actual.format) .. "', actual codec='" .. tostring(actual.codec) .. "'.")
    end
    if not ok then
        append(state.warnings, "Resolve reported no format change, but the current render format read back correctly as "
            .. tostring(actual.format) .. "/" .. tostring(actual.codec) .. ".")
    end
    return formatName, codecName, codecDescription, actual
end

local function outputNameExists(resolveObject, fileName)
    local mediaStorage = resolveObject:GetMediaStorage()
    if not mediaStorage then return false end
    local listed = mediaStorage:GetFileList(OUTPUT_DIR) or {}
    for _, listedPath in ipairs(listed) do
        if string.lower(basename(listedPath)) == string.lower(fileName) then return true end
    end
    return false
end

local function collisionSafeOutputBase(resolveObject, fileName)
    local base = stem(fileName) .. "_Rec709_Standard_Test"
    local candidate = base
    if outputNameExists(resolveObject, candidate .. ".mp4") then
        local suffix = os.date("%Y%m%d_%H%M%S")
        candidate = base .. "_" .. suffix
        local number = 2
        while outputNameExists(resolveObject, candidate .. ".mp4") do
            candidate = base .. "_" .. suffix .. "_" .. tostring(number)
            number = number + 1
        end
    end
    return candidate
end

local function addRenderJobForClip(resolveObject, project, timeline, fileName)
    local timelineSet = project:SetCurrentTimeline(timeline)
    local currentTimeline = project:GetCurrentTimeline()
    if not timelineSet and (not currentTimeline or currentTimeline:GetName() ~= timeline:GetName()) then
        fail("Could not select timeline " .. timeline:GetName())
    end
    local renderModeSet = project:SetCurrentRenderMode(0)
    local actualRenderMode = project:GetCurrentRenderMode()
    if tonumber(actualRenderMode) ~= 0 then fail("Could not select and verify Individual Clips render mode.") end
    if not renderModeSet then
        append(state.warnings, "Resolve reported no render-mode change, but Individual Clips mode read back as 0.")
    end

    local formatName, codecName, codecDescription, actualFormat = chooseMp4H264(project)
    local outputBase = collisionSafeOutputBase(resolveObject, fileName)
    local outputPath = OUTPUT_DIR .. "/" .. outputBase .. ".mp4"
    -- Resolve 20.3.2 Free can apply valid encoder settings while returning false
    -- for a multi-key SetRenderSettings call. Submit the officially documented
    -- keys one at a time so an encoder-specific rejection cannot discard the
    -- collision-safe target path, clip name, geometry, or frame rate.
    local documentedSettings = {
        {"SelectAllFrames", true},
        {"TargetDir", OUTPUT_DIR},
        {"CustomName", outputBase},
        {"ExportVideo", true},
        {"ExportAudio", true},
        {"FormatWidth", 3840},
        {"FormatHeight", 2160},
        {"FrameRate", 59.94},
        {"VideoQuality", 100000},
        {"AudioCodec", "aac"},
        {"AudioSampleRate", 48000},
        {"ColorSpaceTag", "Same as Project"},
        {"GammaTag", "Same as Project"},
        {"ReplaceExistingFilesInPlace", false}
    }
    local rejectedSettingNames = {}
    for _, entry in ipairs(documentedSettings) do
        local setting = {}
        setting[entry[1]] = entry[2]
        if not project:SetRenderSettings(setting) then
            append(rejectedSettingNames, entry[1])
        end
    end
    if #rejectedSettingNames > 0 then
        append(state.warnings,
            "Resolve returned false for these individually submitted documented render settings for "
            .. fileName .. ": " .. table.concat(rejectedSettingNames, ", ")
            .. ". The job was added only after setting the collision-safe TargetDir/CustomName and the locked 59.94 timeline; actual job fields are recorded below.")
    end

    local jobId = project:AddRenderJob()
    if not jobId or tostring(jobId) == "" then fail("Could not add render job for " .. fileName) end
    append(state.render_jobs, tostring(jobId) .. " | " .. timeline:GetName() .. " | " .. outputPath)
    append(state.outputs, outputPath)

    state.render_settings["render_mode"] = tostring(project:GetCurrentRenderMode()) .. " (0 = Individual Clips)"
    state.render_settings["format"] = actualFormat.format or formatName
    state.render_settings["video_codec"] = actualFormat.codec or codecName
    state.render_settings["video_codec_description"] = codecDescription or "H.264"
    state.render_settings["resolution"] = "3840x2160"
    state.render_settings["frame_rate"] = "59.94"
    state.render_settings["video_quality_requested_kbps"] = "100000"
    state.render_settings["audio_codec_requested"] = "aac"
    state.render_settings["audio_sample_rate_requested"] = "48000"
    state.render_settings["audio_bitrate"] = "Not exposed by the documented 20.3.2 SetRenderSettings keys; encoder preset/default"
    state.render_settings["replace_existing_files"] = "false"
end

local function describeRenderJobs(project)
    local jobs = project:GetRenderJobList() or {}
    for _, job in ipairs(jobs) do
        local fields = {}
        for key, value in pairs(job) do
            if scalar(value) then append(fields, tostring(key) .. "=" .. tostring(value)) end
        end
        table.sort(fields)
        if #fields > 0 then append(state.render_jobs, "API job snapshot: " .. table.concat(fields, "; ")) end
    end
end

local function phaseOne(resolveObject, project)
    state.phase = "PHASE_1_CONFIGURING_AND_IMPORTING_ONE_CLIP"
    configureProject(project)

    local firstName = TEST_FILES[1]
    local firstPath = INPUT_DIR .. "/" .. firstName
    local firstClip = importOne(project, firstPath)
    append(state.imported_files, firstName)
    setInputColorSpace(project, firstClip, firstName)

    local properties = firstClip:GetClipProperty() or {}
    local codec = properties["Video Codec"] or properties["Codec"] or "not reported"
    local resolution = properties["Resolution"] or "not reported"
    local fps = properties["FPS"] or properties["Frame Rate"] or "not reported"
    append(state.warnings, "Compatibility clip API properties: codec=" .. tostring(codec) .. ", resolution=" .. tostring(resolution) .. ", fps=" .. tostring(fps) .. ". Visual viewer confirmation is still required.")

    local timeline = project:GetMediaPool():CreateTimelineFromClips(COMPAT_TIMELINE, {firstClip})
    if not timeline then fail("Could not create the one-clip compatibility timeline.") end
    setTimelineGeometry(timeline)
    project:SetCurrentTimeline(timeline)
    resolveObject:GetProjectManager():SaveProject()

    state.compatibility = "AWAITING VISUAL CHECK: inspect thumbnail and Edit viewer for image, Media Offline, or audio-only behavior. Do not run phase two unless valid."
    state.phase = "AWAITING_HEVC_VISUAL_CONFIRMATION"
    writeReport()
    resolveObject:OpenPage("edit")
    local startTimecode = timeline:GetStartTimecode()
    if startTimecode and tostring(startTimecode) ~= "" then timeline:SetCurrentTimecode(startTimecode) end
    print("FX3_AUTOGRADE_PHASE_1_READY")
end

local function phaseTwo(resolveObject, project)
    state.phase = "PHASE_2_PREPARING_THREE_RENDER_JOBS"
    state.compatibility = "CONFIRMED by the controlled Edit viewer check before phase two: image visible, not Media Offline, and not audio-only."

    configureProject(project)
    local clips = {}
    for _, fileName in ipairs(TEST_FILES) do
        local fullPath = INPUT_DIR .. "/" .. fileName
        local clip = importOne(project, fullPath)
        clips[fileName] = clip
        append(state.imported_files, fileName)
        setInputColorSpace(project, clip, fileName)
    end

    for _, fileName in ipairs(TEST_FILES) do
        local timelineName = "Render_" .. stem(fileName)
        local timeline = findTimeline(project, timelineName)
        if timeline then
            if #(project:GetRenderJobList() or {}) ~= 0 then
                fail("A render timeline and render jobs already exist; refusing to duplicate or overwrite them: " .. timelineName)
            end
            verifyOneClipTimeline(timeline, fileName)
            append(state.warnings, "Safely reusing the verified one-clip render timeline left by the prior pre-queue stop: " .. timelineName)
        else
            timeline = project:GetMediaPool():CreateTimelineFromClips(timelineName, {clips[fileName]})
            if not timeline then fail("Could not create render timeline " .. timelineName) end
        end
        setTimelineGeometry(timeline)
        addRenderJobForClip(resolveObject, project, timeline, fileName)
    end

    append(state.warnings, "The official 20.3.2 API does not document an AAC bitrate key. AAC 48 kHz was requested; 320 kb/s cannot be guaranteed through the documented API and must be checked in the Deliver UI/job output.")
    describeRenderJobs(project)
    resolveObject:GetProjectManager():SaveProject()
    state.phase = "THREE_RENDER_JOBS_QUEUED_AWAITING_RENDER_START"
    writeReport()
    resolveObject:OpenPage("deliver")
    print("FX3_AUTOGRADE_PHASE_2_READY")
end

local function startOnlyVerifiedTestJobs(resolveObject, project, jobs)
    if #jobs ~= #TEST_FILES then
        fail("The isolated test project has " .. tostring(#jobs) .. " queued jobs, not exactly three. Refusing to start rendering.")
    end

    local expectedByTimeline = {}
    for _, fileName in ipairs(TEST_FILES) do
        expectedByTimeline["Render_" .. stem(fileName)] = stem(fileName) .. "_Rec709_Standard_Test"
    end

    local jobIds = {}
    for _, job in ipairs(jobs) do
        local timelineName = tostring(job.TimelineName or "")
        local expectedOutputPrefix = expectedByTimeline[timelineName]
        local outputFileName = tostring(job.OutputFilename or "")
        local targetDir = string.lower(tostring(job.TargetDir or "")):gsub("\\", "/")
        local formatOk = normalizeText(job.VideoFormat) == "mp4"
        local codecOk = contains(job.VideoCodec, "h.264") or contains(job.VideoCodec, "h264")
        local outputNameOk = expectedOutputPrefix
            and string.sub(outputFileName, 1, #expectedOutputPrefix) == expectedOutputPrefix
            and string.lower(string.sub(outputFileName, -4)) == ".mp4"
        local targetOk = string.sub(targetDir, -16) == "ship_output/test"
        local geometryOk = tonumber(job.FormatWidth) == 3840 and tonumber(job.FormatHeight) == 2160
        local frameRateOk = valueEqualsNumber(job.FrameRate, 59.94)
        local audioOk = job.IsExportAudio == true and normalizeText(job.AudioCodec) == "aac"
            and tonumber(job.AudioSampleRate) == 48000
        local modeOk = contains(job.RenderMode, "individual")
        local jobId = job.JobId or job.RenderJobId
        if not (expectedOutputPrefix and outputNameOk and targetOk and formatOk and codecOk
            and geometryOk and frameRateOk and audioOk and modeOk and jobId) then
            fail("Queued render job verification failed for timeline '" .. timelineName
                .. "'. Refusing to start any render.")
        end
        append(jobIds, tostring(jobId))
        expectedByTimeline[timelineName] = nil
    end
    for timelineName, _ in pairs(expectedByTimeline) do
        fail("The expected test job is missing for timeline " .. timelineName .. ". Refusing to start rendering.")
    end

    if project:IsRenderingInProgress() then
        fail("Resolve is already rendering. Refusing to start another render operation.")
    end
    local started = project:StartRendering(jobIds, true)
    if not started then fail("Resolve refused to start the three verified test render jobs.") end
    resolveObject:OpenPage("deliver")
    print("FX3_AUTOGRADE_THREE_TEST_RENDERS_STARTED")
end

local function main()
    local resolveObject = getResolveObject()
    if not resolveObject then fail("No internal Resolve object is available. Run this script from Workspace > Scripts inside Resolve.") end
    local projectManager = resolveObject:GetProjectManager()
    if not projectManager then fail("Resolve did not return a ProjectManager object.") end

    local project = projectManager:GetCurrentProject()
    if project and project:GetName() ~= PROJECT_NAME then
        fail("A different project is open ('" .. tostring(project:GetName()) .. "'). Return to Project Manager; do not modify that project.")
    end

    if not project then
        if projectExists(projectManager, PROJECT_NAME) then
            fail("A project named " .. PROJECT_NAME .. " already exists. Refusing to load, replace, or overwrite it automatically.")
        end
        project = projectManager:CreateProject(PROJECT_NAME, PROJECT_ROOT .. "/temp")
        if not project then fail("Could not create the unique test project " .. PROJECT_NAME) end
    end

    local existingCompatibilityTimeline = findTimeline(project, COMPAT_TIMELINE)
    if existingCompatibilityTimeline and not valueEqualsNumber(existingCompatibilityTimeline:GetSetting("timelinePlaybackFrameRate"), 59.94) then
        local fileBackedCount = 0
        local unexpectedFileBackedClip = false
        for _, item in ipairs(rootClips(project)) do
            local path = clipFilePath(item)
            if path ~= "" then
                fileBackedCount = fileBackedCount + 1
                if string.lower(basename(path)) ~= string.lower(TEST_FILES[1]) then unexpectedFileBackedClip = true end
            end
        end
        local safeRecoveryState = project:GetTimelineCount() == 1 and fileBackedCount == 1 and not unexpectedFileBackedClip
        if not safeRecoveryState then
            fail("The compatibility timeline is not 59.94 and the project is not in the exact one-clip recovery state. Refusing automatic recovery.")
        end

        append(state.warnings, "The original root-folder test project was preserved because its compatibility timeline was locked at 24 fps. A clean same-named project is being created in Resolve project folder '" .. RECOVERY_PROJECT_FOLDER .. "'; no project is overwritten or deleted.")
        if not projectManager:SaveProject() then fail("Could not save the preserved 24 fps test project before recovery.") end
        if not projectManager:CloseProject(project) then fail("Could not close the preserved 24 fps test project before recovery.") end
        if not projectManager:GotoRootFolder() then fail("Could not navigate to the Resolve project root folder for recovery.") end
        for _, folderName in ipairs(projectManager:GetFolderListInCurrentFolder() or {}) do
            if folderName == RECOVERY_PROJECT_FOLDER then
                fail("The unique recovery project folder already exists; refusing to reuse or overwrite it: " .. RECOVERY_PROJECT_FOLDER)
            end
        end
        if not projectManager:CreateFolder(RECOVERY_PROJECT_FOLDER) then fail("Could not create the unique recovery project folder.") end
        if not projectManager:OpenFolder(RECOVERY_PROJECT_FOLDER) then fail("Could not open the unique recovery project folder.") end
        if projectExists(projectManager, PROJECT_NAME) then fail("A same-named project already exists in the recovery folder; refusing to overwrite it.") end
        project = projectManager:CreateProject(PROJECT_NAME, PROJECT_ROOT .. "/temp")
        if not project then fail("Could not create the clean 59.94 test project in the recovery folder.") end
    end

    local compatibilityTimeline = findTimeline(project, COMPAT_TIMELINE)
    if not compatibilityTimeline then
        local existingClips = rootClips(project)
        local isSafePhaseOneResume = project:GetTimelineCount() == 0
            and #existingClips == 1
            and string.lower(basename(clipFilePath(existingClips[1]))) == string.lower(TEST_FILES[1])
        if project:GetTimelineCount() ~= 0 or (#existingClips ~= 0 and not isSafePhaseOneResume) then
            fail("The target project is not empty and lacks the script's compatibility timeline. Refusing to modify it.")
        end
        if isSafePhaseOneResume then
            append(state.warnings, "Resuming phase one from the one expected compatibility clip after a prior verified stop; no other clips or timelines were present.")
        end
        phaseOne(resolveObject, project)
        return
    end

    local existingRenderJobs = project:GetRenderJobList() or {}
    if #existingRenderJobs > 0 then
        startOnlyVerifiedTestJobs(resolveObject, project, existingRenderJobs)
        return
    end

    phaseTwo(resolveObject, project)
end

local ok, message = pcall(main)
if not ok then
    if #state.failures == 0 then append(state.failures, tostring(message)) end
    state.phase = "FAILED"
    writeReport()
    print("FX3_AUTOGRADE_FAILED: " .. tostring(message))
end
